spring.application.name=my-application
server.port=8081
# for Spring Boot 2.2.x+
logging.file.name=/usr/local/myapplication/log/my-application.log
# for older Spring Boot versions
logging.file=/usr/local/myapplication/log/my-application.log
# TtlMDCAdapterInitializer生效方式2
# 无需启动加载获得MDCAdapter，由StaticMDCBinder提供给MDC加载创建
context.initializer.classes=ThreadLocal.TtlMDCAdapterInitializer

