spring.application.name=my-application
server.port=8081
# for Spring Boot 2.2.x+
logging.file.name=/usr/local/myapplication/log/my-application.log
# for older Spring Boot versions
logging.file=/usr/local/myapplication/log/my-application.log